spring:
  application:
    name: tiaadeals-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/tiaadeals
    username: tiaadeals_user
    password: ${DB_PASSWORD:tiaadeals_password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Security Configuration
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.tiaadeals.backend: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: ./logs/tiaadeals-backend.log
    max-size: 10MB
    max-history: 30

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: 604800000 # 7 days in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /docs.json
  swagger-ui:
    path: /docs
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: TiaaDeals API
    version: 1.0.0
    description: A comprehensive e-commerce API for TiaaDeals platform
    contact:
      name: TiaaDeals API Support
      email: support@tiaadeals.com
      url: https://tiaadeals.com/support
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT

# Environment-specific configurations
---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tiaadeals_dev

logging:
  level:
    com.tiaadeals.backend: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tiaadeals}
    username: ${DB_USER:tiaadeals_user}
    password: ${DB_PASSWORD}

logging:
  level:
    com.tiaadeals.backend: WARN
    root: WARN
